<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button - register yes (regist)</name>
   <tag></tag>
   <elementGuidId>5db15d8c-e14e-441a-88fb-d10f7fc976a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-fw.fa-check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='wt45_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords1_ctl03_wt7']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-fw fa-check</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt45_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords1_ctl03_wt7&quot;)/span[@class=&quot;fa fa-fw fa-check&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='wt45_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords1_ctl03_wt7']/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
   </webElementXpaths>
</WebElementEntity>
