<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button - Logout</name>
   <tag></tag>
   <elementGuidId>551900aa-0f78-4ba9-8ab3-2c456900353e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@title, 'Logout') and (contains(text(), 'Logout') or contains(., 'Logout'))]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wt26_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt5_OutSystemsUIWeb_wt12_block_wtFooter_wt10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='wt26_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt5_OutSystemsUIWeb_wt12_block_wtFooter_wt10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wt26_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt5_OutSystemsUIWeb_wt12_block_wtFooter_wt10</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>32</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Logout</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('wt26$OutSystemsUIWeb_wt4$block$wtHeader$wtRight$wt5$OutSystemsUIWeb_wt12$block$wtFooter$wt10','')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Logout</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt26_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt5_OutSystemsUIWeb_wt12_block_wtFooter_wt10&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='wt26_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt5_OutSystemsUIWeb_wt12_block_wtFooter_wt10']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wt26_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt5_OutSystemsUIWeb_wt12_block_wtFooter']/div/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Logout')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ProMAG'])[2]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[3]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Transaction :'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('wt26$OutSystemsUIWeb_wt4$block$wtHeader$wtRight$wt5$OutSystemsUIWeb_wt12$block$wtFooter$wt10','')&quot;)]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'wt26_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt5_OutSystemsUIWeb_wt12_block_wtFooter_wt10' and @title = 'Logout' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;wt26$OutSystemsUIWeb_wt4$block$wtHeader$wtRight$wt5$OutSystemsUIWeb_wt12$block$wtFooter$wt10&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = ' Logout' or . = ' Logout')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='wt20_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt4_OutSystemsUIWeb_wt12_block_wtFooter_wt10']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wt20_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt4_OutSystemsUIWeb_wt12_block_wtFooter']/div/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incoming Project :'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('wt20$OutSystemsUIWeb_wt4$block$wtHeader$wtRight$wt4$OutSystemsUIWeb_wt12$block$wtFooter$wt10','')&quot;)]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'wt20_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt4_OutSystemsUIWeb_wt12_block_wtFooter_wt10' and @title = 'Logout' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;wt20$OutSystemsUIWeb_wt4$block$wtHeader$wtRight$wt4$OutSystemsUIWeb_wt12$block$wtFooter$wt10&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = ' Logout' or . = ' Logout')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='wt13_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt3_OutSystemsUIWeb_wt12_block_wtFooter_wt10']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wt13_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt3_OutSystemsUIWeb_wt12_block_wtFooter']/div/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here to see your activities'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('wt13$OutSystemsUIWeb_wt4$block$wtHeader$wtRight$wt3$OutSystemsUIWeb_wt12$block$wtFooter$wt10','')&quot;)]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'wt13_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt3_OutSystemsUIWeb_wt12_block_wtFooter_wt10' and @title = 'Logout' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;wt13$OutSystemsUIWeb_wt4$block$wtHeader$wtRight$wt3$OutSystemsUIWeb_wt12$block$wtFooter$wt10&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = ' Logout' or . = ' Logout')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='wt12_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt3_OutSystemsUIWeb_wt12_block_wtFooter_wt10']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wt12_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt3_OutSystemsUIWeb_wt12_block_wtFooter']/div/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('wt12$OutSystemsUIWeb_wt4$block$wtHeader$wtRight$wt3$OutSystemsUIWeb_wt12$block$wtFooter$wt10','')&quot;)]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'wt12_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt3_OutSystemsUIWeb_wt12_block_wtFooter_wt10' and @title = 'Logout' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;wt12$OutSystemsUIWeb_wt4$block$wtHeader$wtRight$wt3$OutSystemsUIWeb_wt12$block$wtFooter$wt10&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = ' Logout' or . = ' Logout')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='wt12_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt3_OutSystemsUIWeb_wt11_block_wtFooter_wt9']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wt12_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt3_OutSystemsUIWeb_wt11_block_wtFooter']/div/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='shaziawaud...'])[2]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('wt12$OutSystemsUIWeb_wt4$block$wtHeader$wtRight$wt3$OutSystemsUIWeb_wt11$block$wtFooter$wt9','')&quot;)]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'wt12_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt3_OutSystemsUIWeb_wt11_block_wtFooter_wt9' and @title = 'Logout' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;wt12$OutSystemsUIWeb_wt4$block$wtHeader$wtRight$wt3$OutSystemsUIWeb_wt11$block$wtFooter$wt9&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = ' Logout' or . = ' Logout')]</value>
   </webElementXpaths>
</WebElementEntity>
