<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>card - user profile</name>
   <tag></tag>
   <elementGuidId>39ff391d-6266-4f12-9e47-c7feae759c73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'wt22_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt5_OutSystemsUIWeb_wt17_block_wtContent']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wt22_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt5_OutSystemsUIWeb_wt17_block_wtContent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wt22_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt5_OutSystemsUIWeb_wt17_block_wtContent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wt22_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt5_OutSystemsUIWeb_wt17_block_wtContent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>center-align flex-direction-row</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ProMAG</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt22_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt5_OutSystemsUIWeb_wt17_block_wtContent&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='wt22_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt5_OutSystemsUIWeb_wt17_block_wtContent']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='wt22_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt5']/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ProMAG'])[1]/following::div[14]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::div[19]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'wt22_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt5_OutSystemsUIWeb_wt17_block_wtContent' and (text() = 'ProMAG' or . = 'ProMAG')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='wt20_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt4_OutSystemsUIWeb_wt17_block_wtContent']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='wt20_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt4']/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'wt20_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt4_OutSystemsUIWeb_wt17_block_wtContent' and (text() = 'ProMAG' or . = 'ProMAG')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='wt12_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt3_OutSystemsUIWeb_wt17_block_wtContent']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='wt12_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt3']/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'wt12_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt3_OutSystemsUIWeb_wt17_block_wtContent' and (text() = 'ProMAG' or . = 'ProMAG')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='wt12_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt3_OutSystemsUIWeb_wt15_block_wtContent']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='shaziawaud...'])[1]/following::div[14]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'wt12_OutSystemsUIWeb_wt4_block_wtHeader_wtRight_wt3_OutSystemsUIWeb_wt15_block_wtContent' and (text() = 'shaziawaud...' or . = 'shaziawaud...')]</value>
   </webElementXpaths>
</WebElementEntity>
