<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button - action - edit</name>
   <tag></tag>
   <elementGuidId>c1b03754-4640-47a1-abc2-d8efa89dec8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tr[${row}]/td[3]/div/a/span[count(. | //*[@class = 'fa fa-fw fa-edit']) = count(//*[@class = 'fa fa-fw fa-edit'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='wt19_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords1_ctl03_wt69']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-fw.fa-edit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-fw fa-edit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tr[${row}]/td[3]/div/a/span</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='wt19_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords1_ctl03_wt69']/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='wt19_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords1_ctl05_wt69']/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/a/span</value>
   </webElementXpaths>
</WebElementEntity>
