<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input - edit - Item Name</name>
   <tag></tag>
   <elementGuidId>d49a4729-57fc-4374-9ca2-cdd1ed384af6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wt19_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wtModalEdit_block_wtContent_wt65']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and contains(@id, 'ModalEdit') and @class = 'input OSFillParent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wt19_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wtModalEdit_block_wtContent_wt65</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wt19$OutSystemsUIWeb_wt4$block$wtContent$wtMainContent$OutSystemsUIWeb_wtModalEdit$block$wtContent$wt65</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ini psa item</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ModalEdit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input OSFillParent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt19_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wtModalEdit_block_wtContent_wt65&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wt19_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wtModalEdit_block_wtContent_wt65']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wt19_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wtModalEdit_block_wtContent']/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div[2]/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'wt19$OutSystemsUIWeb_wt4$block$wtContent$wtMainContent$OutSystemsUIWeb_wtModalEdit$block$wtContent$wt65' and @type = 'text' and @id = 'wt19_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wtModalEdit_block_wtContent_wt65']</value>
   </webElementXpaths>
</WebElementEntity>
