<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input - old password</name>
   <tag></tag>
   <elementGuidId>e72ed22c-fcf9-4990-85d6-29a5cca0fd93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wt59_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt4_block_wtContent_wt10']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wt59_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt4_block_wtContent_wt10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wt59$OutSystemsUIWeb_wt4$block$wtContent$wtMainContent$OutSystemsUIWeb_wt4$block$wtContent$wt10</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wt59_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt4_block_wtContent_wt10</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>48</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input OSFillParent Mandatory</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('wt59_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt4_block_wtContent_wt2', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt59_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt4_block_wtContent_wt10&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wt59_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt4_block_wtContent_wt10']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wt59_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt4_block_wtContent']/div[5]/div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'wt59$OutSystemsUIWeb_wt4$block$wtContent$wtMainContent$OutSystemsUIWeb_wt4$block$wtContent$wt10' and @type = 'password' and @id = 'wt59_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt4_block_wtContent_wt10']</value>
   </webElementXpaths>
</WebElementEntity>
