<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox - Test Item - Active</name>
   <tag></tag>
   <elementGuidId>a3e10ec9-7ba6-40c4-b5c8-36140a2080b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tr[${row}]/td[6]/span/span/div/div/input[count(. | //*[@type = 'checkbox' and @class = 'checkbox']) = count(//*[@type = 'checkbox' and @class = 'checkbox'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wt14_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt46_block_wtContent_wtTableRecords1_ctl04_wt62_OutSystemsUIWeb_wt3_block_wtCheckBox_wt1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wt14_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt46_block_wtContent_wtTableRecords1_ctl04_wt62_OutSystemsUIWeb_wt3_block_wtCheckBox_wt1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wt14$OutSystemsUIWeb_wt4$block$wtContent$wtMainContent$OutSystemsUIWeb_wt46$block$wtContent$wtTableRecords1$ctl04$wt62$OutSystemsUIWeb_wt3$block$wtCheckBox$wt1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wt14_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt46_block_wtContent_wtTableRecords1_ctl04_wt62_OutSystemsUIWeb_wt3_block_wtCheckBox_wt1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>47</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OsAjax(arguments[0] || window.event,'wt14_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt46_block_wtContent_wtTableRecords1_ctl04_wt62_OutSystemsUIWeb_wt3_block_wtCheckBox_wt1','wt14$OutSystemsUIWeb_wt4$block$wtContent$wtMainContent$OutSystemsUIWeb_wt46$block$wtContent$wtTableRecords1$ctl04$wt62$OutSystemsUIWeb_wt3$block$wtCheckBox$wt1','Change','__OSVSTATE,','');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tr[${row}]/td[6]/span/span/div/div/input</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wt14_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt46_block_wtContent_wtTableRecords1_ctl04_wt62_OutSystemsUIWeb_wt3_block_wtCheckBox_wt1']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wt14_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt46_block_wtContent_wtTableRecords1_ctl04_wt62_OutSystemsUIWeb_wt3_block_wtCheckBox']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[6]/span/span/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'wt14$OutSystemsUIWeb_wt4$block$wtContent$wtMainContent$OutSystemsUIWeb_wt46$block$wtContent$wtTableRecords1$ctl04$wt62$OutSystemsUIWeb_wt3$block$wtCheckBox$wt1' and @checked = 'checked' and @id = 'wt14_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt46_block_wtContent_wtTableRecords1_ctl04_wt62_OutSystemsUIWeb_wt3_block_wtCheckBox_wt1']</value>
   </webElementXpaths>
</WebElementEntity>
