<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text - alert - User berhasil diubah</name>
   <tag></tag>
   <elementGuidId>9a6a6a5d-2a16-4b0f-bcc3-d98b7ae0c4f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'wt14_OutSystemsUIWeb_wt4_block_wt5_RichWidgets_wt7_block_wtSanitizedHtml' and @class = 'Feedback_Message_Text' and (text() = 'User berhasil diubah!' or . = 'User berhasil diubah!')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='wt14_OutSystemsUIWeb_wt4_block_wt5_RichWidgets_wt7_block_wtSanitizedHtml']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wt14_OutSystemsUIWeb_wt4_block_wt5_RichWidgets_wt7_block_wtSanitizedHtml</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wt14_OutSystemsUIWeb_wt4_block_wt5_RichWidgets_wt7_block_wtSanitizedHtml</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Feedback_Message_Text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User berhasil diubah!</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt14_OutSystemsUIWeb_wt4_block_wt5_RichWidgets_wt7_block_wtSanitizedHtml&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='wt14_OutSystemsUIWeb_wt4_block_wt5_RichWidgets_wt7_block_wtSanitizedHtml']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wt14_OutSystemsUIWeb_wt4_block_wt5_RichWidgets_wt7_block_wtFeedback_Wrapper']/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to Content (Press Enter)'])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACC - ProMAG'])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User berhasil diubah!']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'wt14_OutSystemsUIWeb_wt4_block_wt5_RichWidgets_wt7_block_wtSanitizedHtml' and (text() = 'User berhasil diubah!' or . = 'User berhasil diubah!')]</value>
   </webElementXpaths>
</WebElementEntity>
