<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input - Password</name>
   <tag></tag>
   <elementGuidId>fa792b44-02cc-4e4d-8e29-5d6c6dd24c61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OutSystemsUIWeb_wt12_block_wtLogin_OutSystemsUIWeb_wt13_block_wtLogin_OutSystemsUIWeb_wt5_block_wtInput_wtPasswordInput']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'OutSystemsUIWeb_wt12$block$wtLogin$OutSystemsUIWeb_wt13$block$wtLogin$OutSystemsUIWeb_wt5$block$wtInput$wtPasswordInput' and @type = 'password' and @id = 'OutSystemsUIWeb_wt12_block_wtLogin_OutSystemsUIWeb_wt13_block_wtLogin_OutSystemsUIWeb_wt5_block_wtInput_wtPasswordInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OutSystemsUIWeb_wt12_block_wtLogin_OutSystemsUIWeb_wt13_block_wtLogin_OutSystemsUIWeb_wt5_block_wtInput_wtPasswordInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OutSystemsUIWeb_wt12$block$wtLogin$OutSystemsUIWeb_wt13$block$wtLogin$OutSystemsUIWeb_wt5$block$wtInput$wtPasswordInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OutSystemsUIWeb_wt12_block_wtLogin_OutSystemsUIWeb_wt13_block_wtLogin_OutSystemsUIWeb_wt5_block_wtInput_wtPasswordInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input OSFillParent Mandatory</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('OutSystemsUIWeb_wt12_block_wtLogin_OutSystemsUIWeb_wt13_block_wtLogin_wt33', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OutSystemsUIWeb_wt12_block_wtLogin_OutSystemsUIWeb_wt13_block_wtLogin_OutSystemsUIWeb_wt5_block_wtInput_wtPasswordInput&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OutSystemsUIWeb_wt12_block_wtLogin_OutSystemsUIWeb_wt13_block_wtLogin_OutSystemsUIWeb_wt5_block_wtInput_wtPasswordInput']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OutSystemsUIWeb_wt12_block_wtLogin_OutSystemsUIWeb_wt13_block_wtLogin_OutSystemsUIWeb_wt5_block_wtInput']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'OutSystemsUIWeb_wt12$block$wtLogin$OutSystemsUIWeb_wt13$block$wtLogin$OutSystemsUIWeb_wt5$block$wtInput$wtPasswordInput' and @type = 'password' and @id = 'OutSystemsUIWeb_wt12_block_wtLogin_OutSystemsUIWeb_wt13_block_wtLogin_OutSystemsUIWeb_wt5_block_wtInput_wtPasswordInput']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OutSystemsUIWeb_wt13_block_wtLogin_OutSystemsUIWeb_wt14_block_wtLogin_OutSystemsUIWeb_wt6_block_wtInput_wtPasswordInput']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OutSystemsUIWeb_wt13_block_wtLogin_OutSystemsUIWeb_wt14_block_wtLogin_OutSystemsUIWeb_wt6_block_wtInput']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'OutSystemsUIWeb_wt13$block$wtLogin$OutSystemsUIWeb_wt14$block$wtLogin$OutSystemsUIWeb_wt6$block$wtInput$wtPasswordInput' and @type = 'password' and @id = 'OutSystemsUIWeb_wt13_block_wtLogin_OutSystemsUIWeb_wt14_block_wtLogin_OutSystemsUIWeb_wt6_block_wtInput_wtPasswordInput']</value>
   </webElementXpaths>
</WebElementEntity>
