<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input - NPK</name>
   <tag></tag>
   <elementGuidId>16149297-b2bb-4744-8c1c-9160c21b72e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OutSystemsUIWeb_wt12_block_wtLogin_OutSystemsUIWeb_wt13_block_wtLogin_OutSystemsUIWeb_wt25_block_wtInput_wtUserNameInput']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'OutSystemsUIWeb_wt12$block$wtLogin$OutSystemsUIWeb_wt13$block$wtLogin$OutSystemsUIWeb_wt25$block$wtInput$wtUserNameInput' and @type = 'text' and @id = 'OutSystemsUIWeb_wt12_block_wtLogin_OutSystemsUIWeb_wt13_block_wtLogin_OutSystemsUIWeb_wt25_block_wtInput_wtUserNameInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OutSystemsUIWeb_wt12_block_wtLogin_OutSystemsUIWeb_wt13_block_wtLogin_OutSystemsUIWeb_wt25_block_wtInput_wtUserNameInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OutSystemsUIWeb_wt12$block$wtLogin$OutSystemsUIWeb_wt13$block$wtLogin$OutSystemsUIWeb_wt25$block$wtInput$wtUserNameInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OutSystemsUIWeb_wt12_block_wtLogin_OutSystemsUIWeb_wt13_block_wtLogin_OutSystemsUIWeb_wt25_block_wtInput_wtUserNameInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input OSFillParent Mandatory</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('OutSystemsUIWeb_wt12_block_wtLogin_OutSystemsUIWeb_wt13_block_wtLogin_wt33', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OutSystemsUIWeb_wt12_block_wtLogin_OutSystemsUIWeb_wt13_block_wtLogin_OutSystemsUIWeb_wt25_block_wtInput_wtUserNameInput&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OutSystemsUIWeb_wt12_block_wtLogin_OutSystemsUIWeb_wt13_block_wtLogin_OutSystemsUIWeb_wt25_block_wtInput_wtUserNameInput']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OutSystemsUIWeb_wt12_block_wtLogin_OutSystemsUIWeb_wt13_block_wtLogin_OutSystemsUIWeb_wt25_block_wtInput']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'OutSystemsUIWeb_wt12$block$wtLogin$OutSystemsUIWeb_wt13$block$wtLogin$OutSystemsUIWeb_wt25$block$wtInput$wtUserNameInput' and @type = 'text' and @id = 'OutSystemsUIWeb_wt12_block_wtLogin_OutSystemsUIWeb_wt13_block_wtLogin_OutSystemsUIWeb_wt25_block_wtInput_wtUserNameInput']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OutSystemsUIWeb_wt13_block_wtLogin_OutSystemsUIWeb_wt14_block_wtLogin_OutSystemsUIWeb_wt27_block_wtInput_wtUserNameInput']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OutSystemsUIWeb_wt13_block_wtLogin_OutSystemsUIWeb_wt14_block_wtLogin_OutSystemsUIWeb_wt27_block_wtInput']/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'OutSystemsUIWeb_wt13$block$wtLogin$OutSystemsUIWeb_wt14$block$wtLogin$OutSystemsUIWeb_wt27$block$wtInput$wtUserNameInput' and @type = 'text' and @id = 'OutSystemsUIWeb_wt13_block_wtLogin_OutSystemsUIWeb_wt14_block_wtLogin_OutSystemsUIWeb_wt27_block_wtInput_wtUserNameInput']</value>
   </webElementXpaths>
</WebElementEntity>
