<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button - Ok</name>
   <tag></tag>
   <elementGuidId>06dd62f6-2133-4f8c-9ab4-c9a3d16886b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wt17_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wt53</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wt17_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wt53']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wt17$OutSystemsUIWeb_wt18$block$wtContent$wtMainContent$wt53</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ok</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wt17_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wt53</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button Is_Default</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt17_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wt53&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wt17_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wt53']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wt17_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent']/div/div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'wt17$OutSystemsUIWeb_wt18$block$wtContent$wtMainContent$wt53' and @id = 'wt17_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wt53']</value>
   </webElementXpaths>
</WebElementEntity>
