<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox - BE - item 2</name>
   <tag></tag>
   <elementGuidId>5d85b82e-6439-429a-8be4-dfb589140b38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wt17_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wtListRecords3_ctl02_wt36</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wt17_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wtListRecords3_ctl02_wt36']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wt17$OutSystemsUIWeb_wt18$block$wtContent$wtMainContent$wtListRecords3$ctl02$wt36</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wt17_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wtListRecords3_ctl02_wt36</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('wt17_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wt53', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OsAjax(arguments[0] || window.event,'wt17_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wtListRecords3_ctl02_wt36','wt17$OutSystemsUIWeb_wt18$block$wtContent$wtMainContent$wtListRecords3$ctl02$wt36','Change','__OSVSTATE,','');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt17_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wtListRecords3_ctl02_wt36&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wt17_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wtListRecords3_ctl02_wt36']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='wt17_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wtListRecords3']/div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'wt17$OutSystemsUIWeb_wt18$block$wtContent$wtMainContent$wtListRecords3$ctl02$wt36' and @id = 'wt17_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wtListRecords3_ctl02_wt36']</value>
   </webElementXpaths>
</WebElementEntity>
