<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea</name>
   <tag></tag>
   <elementGuidId>5a5e93d8-dab2-428e-9a54-e152c8848584</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='wt11_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtEmailTemplate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wt11_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtEmailTemplate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wt11$OutSystemsUIWeb_wt4$block$wtContent$wtMainContent$wtEmailTemplate</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>50</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wt11_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtEmailTemplate</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input OSFillParent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>OsLimitInput(this,event,2000);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>OsLimitInput(this,event,2000);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('wt11_OutSystemsUIWeb_wt4_block_wtContent_wtFooter_wt4', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dear Udin alaudin,

Semoga pesan ini menjumpai dalam keadaan sehat selalu.
Sehubungan dengan request resource Technocenter pada tanggal 2022-04-03, dengan Request ID REQ11113 berikut kami informasikan 
resource yang akan support untuk project tersebut: 

Nama Project: Generated by automated test (one step) edited
Kebutuhan:
1. Visio edited = 2 Orang
2. Ionic edited = 1 Orang
3. PLSQL edited = 3 Orang
4. Selenium edited = 2 Orang

Mohon kirimkan dokumen pendukung seperti: TD/FD/SIT script/UAT script.
Mohon informasikan juga mengenai list email yang akan dimasukan ke dalam board bug Monday dengan link berikut: shazi2@acc.co.id, udin2@gmail.com, siapa2@email.co.id

Regards
Technocenter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt11_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtEmailTemplate&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='wt11_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtEmailTemplate']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wt11_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent']/textarea</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Template'])[1]/following::textarea[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ProMAG'])[2]/following::textarea[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here to see your activities'])[1]/preceding::textarea[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::textarea[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'wt11$OutSystemsUIWeb_wt4$block$wtContent$wtMainContent$wtEmailTemplate' and @id = 'wt11_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtEmailTemplate' and (text() = 'Dear Udin alaudin,

Semoga pesan ini menjumpai dalam keadaan sehat selalu.
Sehubungan dengan request resource Technocenter pada tanggal 2022-04-03, dengan Request ID REQ11113 berikut kami informasikan 
resource yang akan support untuk project tersebut: 

Nama Project: Generated by automated test (one step) edited
Kebutuhan:
1. Visio edited = 2 Orang
2. Ionic edited = 1 Orang
3. PLSQL edited = 3 Orang
4. Selenium edited = 2 Orang

Mohon kirimkan dokumen pendukung seperti: TD/FD/SIT script/UAT script.
Mohon informasikan juga mengenai list email yang akan dimasukan ke dalam board bug Monday dengan link berikut: shazi2@acc.co.id, udin2@gmail.com, siapa2@email.co.id

Regards
Technocenter' or . = 'Dear Udin alaudin,

Semoga pesan ini menjumpai dalam keadaan sehat selalu.
Sehubungan dengan request resource Technocenter pada tanggal 2022-04-03, dengan Request ID REQ11113 berikut kami informasikan 
resource yang akan support untuk project tersebut: 

Nama Project: Generated by automated test (one step) edited
Kebutuhan:
1. Visio edited = 2 Orang
2. Ionic edited = 1 Orang
3. PLSQL edited = 3 Orang
4. Selenium edited = 2 Orang

Mohon kirimkan dokumen pendukung seperti: TD/FD/SIT script/UAT script.
Mohon informasikan juga mengenai list email yang akan dimasukan ke dalam board bug Monday dengan link berikut: shazi2@acc.co.id, udin2@gmail.com, siapa2@email.co.id

Regards
Technocenter')]</value>
   </webElementXpaths>
</WebElementEntity>
