<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox - PSA - item 1</name>
   <tag></tag>
   <elementGuidId>d6e46248-76e7-4d1c-a89d-9866dec673f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'checkbox' and @name = 'wt1$OutSystemsUIWeb_wt18$block$wtContent$wtMainContent$wtListRecords1$ctl00$wt105' and @id = 'wt1_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wtListRecords1_ctl00_wt105' and contains(@class, 'checkbox')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wt1_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wtListRecords1_ctl00_wt105']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wt1_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wtListRecords1_ctl00_wt105</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wt1$OutSystemsUIWeb_wt18$block$wtContent$wtMainContent$wtListRecords1$ctl00$wt105</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wt1_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wtListRecords1_ctl00_wt105</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('wt1_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wt120', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OsAjax(arguments[0] || window.event,'wt1_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wtListRecords1_ctl00_wt105','wt1$OutSystemsUIWeb_wt18$block$wtContent$wtMainContent$wtListRecords1$ctl00$wt105','Change','__OSVSTATE,','');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt1_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wtListRecords1_ctl00_wt105&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wt1_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wtListRecords1_ctl00_wt105']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='wt1_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wtListRecords1']/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'wt1$OutSystemsUIWeb_wt18$block$wtContent$wtMainContent$wtListRecords1$ctl00$wt105' and @checked = 'checked' and @id = 'wt1_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wtListRecords1_ctl00_wt105']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wt1_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wtListRecords1_ctl00_wt102']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'wt1$OutSystemsUIWeb_wt18$block$wtContent$wtMainContent$wtListRecords1$ctl00$wt102' and @id = 'wt1_OutSystemsUIWeb_wt18_block_wtContent_wtMainContent_wtListRecords1_ctl00_wt102']</value>
   </webElementXpaths>
</WebElementEntity>
