<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input - email</name>
   <tag></tag>
   <elementGuidId>2e63c57b-0340-4ff4-a4e2-41e2713f6ce5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wt61_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt47_block_wtContent_wt2']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'wt61$OutSystemsUIWeb_wt4$block$wtContent$wtMainContent$OutSystemsUIWeb_wt47$block$wtContent$wt2' and @type = 'text' and @id = 'wt61_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt47_block_wtContent_wt2' and @placeholder = 'example@acc.co.id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wt61_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt47_block_wtContent_wt2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wt61$OutSystemsUIWeb_wt4$block$wtContent$wtMainContent$OutSystemsUIWeb_wt47$block$wtContent$wt2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wt61_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt47_block_wtContent_wt2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>47</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input OSFillParent Mandatory SmartInput ReadOnly</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>example@acc.co.id</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('wt61_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt47_block_wtContent_wt50', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt61_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt47_block_wtContent_wt2&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wt61_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt47_block_wtContent_wt2']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wt61_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt47_block_wtContent_wtForm1']/div[3]/div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'wt61$OutSystemsUIWeb_wt4$block$wtContent$wtMainContent$OutSystemsUIWeb_wt47$block$wtContent$wt2' and @type = 'text' and @id = 'wt61_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt47_block_wtContent_wt2' and @placeholder = 'example@acc.co.id']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wt62_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt48_block_wtContent_wt2']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wt62_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt48_block_wtContent_wtForm1']/div[3]/div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'wt62$OutSystemsUIWeb_wt4$block$wtContent$wtMainContent$OutSystemsUIWeb_wt48$block$wtContent$wt2' and @type = 'text' and @id = 'wt62_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wt48_block_wtContent_wt2']</value>
   </webElementXpaths>
</WebElementEntity>
