<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button - delete - delete</name>
   <tag></tag>
   <elementGuidId>cf88e52c-86c4-41ca-9cfe-f32bdbf95f49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wt65_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wtModalDelete_block_wtFooter_wt50']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'submit' and @value = 'Delete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wt65_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wtModalDelete_block_wtFooter_wt50</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OsAjax(arguments[0] || window.event,'wt65_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wtModalDelete_block_wtFooter_wt50','wt65$OutSystemsUIWeb_wt4$block$wtContent$wtMainContent$OutSystemsUIWeb_wtModalDelete$block$wtFooter$wt50','','__OSVSTATE,',''); return false;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wt65$OutSystemsUIWeb_wt4$block$wtContent$wtMainContent$OutSystemsUIWeb_wtModalDelete$block$wtFooter$wt50</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Delete</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wt65_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wtModalDelete_block_wtFooter_wt50</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button ThemeGrid_MarginGutter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt65_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wtModalDelete_block_wtFooter_wt50&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wt65_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wtModalDelete_block_wtFooter_wt50']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wt65_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wtModalDelete_block_wtFooter']/div/input[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'wt65$OutSystemsUIWeb_wt4$block$wtContent$wtMainContent$OutSystemsUIWeb_wtModalDelete$block$wtFooter$wt50' and @id = 'wt65_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_OutSystemsUIWeb_wtModalDelete_block_wtFooter_wt50']</value>
   </webElementXpaths>
</WebElementEntity>
