<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button - action - copy template</name>
   <tag></tag>
   <elementGuidId>34d1d42f-01bb-470f-bdf0-35a6faf98480</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tr[${row}]/td/div[2]/a/span[count(. | //*[@class = 'fa fa-fw fa-copy']) = count(//*[@class = 'fa fa-fw fa-copy'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[${row}]/td/div[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-fw.fa-copy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-fw fa-copy</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tr[${row}]/td/div[2]/a/span</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='wt49_OutSystemsUIWeb_wt4_block_wtContent_wtMainContent_wtTableRecords1_ctl03_wt72']/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/span</value>
   </webElementXpaths>
</WebElementEntity>
